// Source: aliyoussefi/D365-Monitoring/KustoQueries.Exceptions.txt
// Exceptions from non-Web clients (plug-ins, services, etc.)
exceptions
| extend d  = parse_json(details)
| extend cm = parse_json(customMeasurements)
| extend cd = parse_json(customDimensions)
| where cd.client != "Web"
| project
    timestamp, problemId, type, assembly, method,
    d[0].type, d[0].parsedStack[0].line,
    cd.userName, cd.uniqueName,
    client_OS, client_Browser, cd
